import {
  useDisclosure,
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  VStack
} from '@chakra-ui/react'
import CustomInputGroup from '../common/CustomInputGroup'

export default function BudgetPlanModal() {
  const { isOpen, onOpen, onClose } = useDisclosure()
  return (
    <>
      <Button
        colorScheme="blue"
        variant="outline"
        px={8}
        size="sm"
        onClick={onOpen}
      >
        Edit
      </Button>

      <Modal isOpen={isOpen} onClose={onClose} isCentered>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader borderBottom="1px solid #DDD">
            Edit budget plan
          </ModalHeader>
          <ModalCloseButton />
          <ModalBody as={VStack} spacing={5} my={4}>
            <CustomInputGroup
              name="income"
              placeholder="e.g. 5000"
              label="Income"
              error="Income should be at least $1"
            />
            <CustomInputGroup
              name="investments"
              placeholder="e.g. 1000"
              label="Investment amount"
              error="Investment amount should be at least $1"
            />
            <CustomInputGroup
              name="savings"
              placeholder="e.g. 2000"
              label="Saving amount"
              error="Saving amount should be at least $1"
            />
            <CustomInputGroup
              name="expenseBudget"
              placeholder="e.g. 2000"
              label="Expense budget(Autogenerated)"
              isReadOnly
              isDisabled
              value={2000}
            />
          </ModalBody>

          <ModalFooter borderTop="1px solid #DDD">
            <Button mr={3} onClick={onClose}>
              Cancel
            </Button>
            <Button colorScheme="blue">Update plan</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  )
}
